# Generated by Django 2.2.4 on 2019-08-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorie',
            field=models.BooleanField(default=False),
        ),
    ]
